[package]
name = "kvs"
version = "0.1.0"
authors = ["lianxm <lianxm2@gmail.com>"]
description = "A key-value store"
edition = "2021"

[dependencies]
clap = { version = "3.1.9", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
